/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Webhook */
        post: operations["simulate_webhook_webhooks_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_orders__order_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/eval/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eval Summary */
        get: operations["eval_summary_eval_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateAction */
        CandidateAction: {
            /** Action */
            action: string;
            /** Erv */
            erv: number;
        };
        /** DecisionAnalysis */
        DecisionAnalysis: {
            /**
             * Candidate Actions
             * @default []
             */
            candidate_actions: components["schemas"]["CandidateAction"][];
            /** Selected Action */
            selected_action?: string | null;
        };
        /** EvalSummary */
        EvalSummary: {
            /** Seed */
            seed: number;
            /** N Orders */
            n_orders: number;
            reclaim: components["schemas"]["PolicyMetrics"];
            always_retry: components["schemas"]["PolicyMetrics"];
            /** Delta */
            delta: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestResult */
        IngestResult: {
            /** Status */
            status: string;
            /** Event Id */
            event_id: string;
            /** Order Id */
            order_id: string;
            /** Action Id */
            action_id?: number | null;
        };
        /** OrderDetail */
        OrderDetail: {
            /** Order Id */
            order_id: string;
            /** Merchant Id */
            merchant_id?: string | null;
            /** Customer Id */
            customer_id?: string | null;
            /** Amount */
            amount: number;
            /** Currency */
            currency: string;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
            /**
             * Payment Attempts
             * @default []
             */
            payment_attempts: components["schemas"]["PaymentAttemptSchema"][];
            /**
             * Recovery Actions
             * @default []
             */
            recovery_actions: components["schemas"]["RecoveryActionSchema"][];
            decision_analysis: components["schemas"]["DecisionAnalysis"];
        };
        /** OrderSummary */
        OrderSummary: {
            /** Order Id */
            order_id: string;
            /** Amount */
            amount: number;
            /** Currency */
            currency: string;
            /** Status */
            status: string;
            /** Created At */
            created_at?: string | null;
        };
        /** PaymentAttemptSchema */
        PaymentAttemptSchema: {
            /** Payment Id */
            payment_id: string;
            /** Attempt Number */
            attempt_number: number;
            /** Method */
            method: string;
            /** Status */
            status: string;
            /** Error Code */
            error_code?: string | null;
            /** Error Reason */
            error_reason?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /** PolicyMetrics */
        PolicyMetrics: {
            /** Recovered Revenue */
            recovered_revenue: number;
            /** Total Revenue At Risk */
            total_revenue_at_risk: number;
            /** Recovery Rate */
            recovery_rate: number;
            /** Unnecessary Interventions */
            unnecessary_interventions: number;
            /** Total Interventions */
            total_interventions: number;
        };
        /** RecoveryActionSchema */
        RecoveryActionSchema: {
            /** Action Id */
            action_id: number;
            /** Action Type */
            action_type: string;
            /** Expected Value */
            expected_value: number;
            /** Status */
            status: string;
            /** Scheduled At */
            scheduled_at?: string | null;
            /** Executed At */
            executed_at?: string | null;
            /** Cancelled At */
            cancelled_at?: string | null;
            /** Reason */
            reason?: string | null;
            /** Explanation */
            explanation?: string | null;
            /** Explanation Model */
            explanation_model?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WebhookPayload */
        WebhookPayload: {
            /**
             * Entity
             * @constant
             */
            entity: "event";
            /** Account Id */
            account_id: string;
            /**
             * Event
             * @enum {string}
             */
            event: "payment.failed" | "payment.captured";
            /** Contains */
            contains?: string[];
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulate_webhook_webhooks_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"][];
                };
            };
        };
    };
    get_order_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eval_summary_eval_summary_get: {
        parameters: {
            query?: {
                n_orders?: number;
                seed?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
